name: PullRequestLintTest

on: pull_request

jobs:
  eslint_prettier:
    name: ESlintAndPrettierCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages
        run: yarn install

      - name: Prettier and ESLint
        run: |
          yarn prettier && \
          yarn lint

      - name: Prettier and ESLint Checks Success
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const ref = "${{github.token}}"
            const pr_num = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pr_num,
              body: "상당히 예쁜 코드네요!",
              event: "APPROVE"
            })
        if: success()

      - name: Prettier and ESLint Checks Fail
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const ref = "${{github.ref}}"
            const pr_num = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pr_num,
              body: "이 코드는 이쁘지 않아요.. Prettier와 ESLint fix해주세요~~",
              event: "REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              pr_num,
              state: "closed"
            })
        if: failure()
