name: PullRequestLintTest

on: pull_request

jobs:
  eslint:
    name: ESlintCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages
        run: yarn install

      - name:
